package com.ailk.biapp.ci.constant;


public class CommonConstants
{

	public static String base = "BJ";
	public static String loginResourceType = "6008";
	public static String logoutResourceType = "6009";
	public static String sqlParallel = "";
	public static String sqlAppend = "";
	public static final String PROJECT_MODEL_DEV = "DEV";
	public static final String PROJECT_MODEL_DEP = "DEP";
	public static final String DATE_FORMAT_YYYYMMDD = "yyyyMMdd";
	public static final String DATE_FORMAT_YYYYMM = "yyyyMM";
	public static final String DATE_FORMAT_YYYY = "yyyy";
	public static final String DATE_FORMAT_YYMM = "yyMM";
	public static final String DATE_FORMAT_YYYY_MM = "yyyy-MM";
	public static final String DATE_FORMAT_YYYY_MM_DD = "yyyy-MM-dd";
	public static final String DATE_FORMAT_YYYY_MM_DD_HHMMSS = "yyyy-MM-dd HH:mm:ss";
	public static final int ALL_VALUE = -1;
	public static final String NO_DATA_TO_DISPLAY = "???????????";
	public static final int FORM_TREND_VALUE = 6;
	public static final int FORM_PAGE_SIZE = 6;
	public static final String DW_LABEL_FORM_TABLE = "DW_LABEL_FORM_TABLE";
	public static final String DW_LABEL_FORM_TABLE_NO_DATE = "DW_LABEL_FORM_TABLE_NO_DATE";
	public static final String NEW_DATE = "NEW_DATE";
	public static int PAGESIZE = 10;
	public static final int ORDER_ASC = 0;
	public static final int ORDER_DESC = 1;
	public static final String CONFIG_PATH = "/config/aibi_ci/ci.properties";
	public static final String CI_STORE_SUB_PATH = "ci";
	public static final String CUST_LIST_TMP_TABLE = "CUST_LIST_TMP_TABLE";
	public static final String CUSTOMER_MAIN_TABEL = "CUSTOMER_MAIN_TABEL";
	public static final String CUST_LIST_TMP_TABLE_POSTFIX = "YYMMDDHHMISSTTTTTT";
	public static final String MAIN_COLUMN = "MAIN_COLUMN";
	public static String MAIN_COLUMN_TYPE = "varchar(32)";
	public static final String BATCH_COUNT = "BATCH_COUNT";
	public static final String TABLE_DIM_LABEL_USE_TYPE = "DIM_LABEL_USE_TYPE";
	public static final String TABLE_DIM_APPROVE_LEVEL = "DIM_APPROVE_LEVEL";
	public static final String TABLE_DIM_APPROVE_RESOURCE_TYPE = "DIM_APPROVE_RESOURCE_TYPE";
	public static final String TABLE_DIM_LABEL_DATA_STATUS = "DIM_LABEL_DATA_STATUS";
	public static final String TABLE_DIM_APPROVE_STATUS = "DIM_APPROVE_STATUS";
	public static final String TABLE_DIM_CUSTOM_CREATE_TYPE = "DIM_CUSTOM_CREATE_TYPE";
	public static final String TABLE_DIM_CUSTOM_DATA_STATUS = "DIM_CUSTOM_DATA_STATUS";
	public static final String TABLE_DIM_BRAND = "DIM_BRAND";
	public static final String TABLE_DIM_VIP_LEVEL = "DIM_VIP_LEVEL";
	public static final String TABLE_DIM_CITY = "DIM_CITY";
	public static final String TABLE_DIM_OP_LOG_TYPE_DETAIL = "DIM_OP_LOG_TYPE_DETAIL";
	public static final String TABLE_DIM_OP_LOG_TYPE = "DIM_OP_LOG_TYPE";
	public static final String TABLE_CI_NEWEST_LABEL_DATE = "CI_NEWEST_LABEL_DATE";
	public static final String TABLE_DIM_SCENE = "DIM_SCENE";
	public static final String TABLE_DIM_CITY_THREAD_CONFIG = "DIM_CITY_THREAD_CONFIG";
	public static final String TABLE_DIM_CITY_DIALY_CUSTOMGROUP_NUM = "DIM_CITY_DIALY_CUSTOMGROUP_NUM";
	public static final String TABLE_DIM_ANNOUNCEMENT_TYPE = "DIM_ANNOUNCEMENT_TYPE";
	public static final String TABLE_DIM_LIST_TACTICS = "DIM_LIST_TACTICS";
	public static final String TABLE_DIM_LABEL_TYPE = "DIM_LABEL_TYPE";
	public static final String EFFECTIVE_LABEL_PREFIX = "LABEL_";
	public static final String ALL_EFFECTIVE_LABEL_MAP = "ALL_EFFECTIVE_LABEL_MAP";
	public static final String EFFECTIVE_LABEL_COLUMN_PREFIX = "COLUMN_";
	public static final String ALL_EFFECTIVE_LABEL_COLUMNS = "ALL_EFFECTIVE_LABEL_COLUMNS";
	public static final String CITY_LABEL = "CITY_";
	public static final String CITY_LABEL_MAP = "CITY_LABEL_MAP";
	public static final String CITY_IDS_LIST = "CITY_IDS_LIST";
	public static final String EFFECTIVE_PRODUCT_PREFIX = "PRODUCT_";
	public static final String ALL_EFFECTIVE_PRODUCT_MAP = "ALL_EFFECTIVE_PRODUCT_MAP";
	public static final String PRODUCT_CATEGORY_PREFIX = "PRODUCT_CATEGORY_";
	public static final String ALL_PRODUCT_CATEGORY_MAP = "ALL_PRODUCT_CATEGORY_MAP";
	public static final String USER_MENU_ITEM = "USER_MENU_ITEM";
	public static final String CI_CUSTOM_LIST_INFO_MAP = "CI_CUSTOM_LIST_INFO_MAP";
	public static final String CI_MARKET_TASK_MAP = "CI_MARKET_TASK_MAP";
	public static final String CI_MARKET_TASK_TREE = "CI_MARKET_TASK_TREE";
	public static final int TEMPLATE_PAGESIZE = 5;
	public static final int CUSTOMER_PAGESIZE = 10;
	public static final int CUSTOMERLIST_PAGESIZE = 5;
	public static final int LOGSTAT_PAGESIZE = 10;
	public static final String LOG_OP_TYPE_PARENTID = "-1";
	public static final String MENU_ID_PREFIX = "93";
	public static final String MONGODB_CONFIG_PATH = "/config/aibi_ci/mongodb.properties";
	public static final String MONGODB_CONFIG_PATH_2 = "/config/aibi_ci/mongodb2.properties";
	public static final String JNDI_MCD = "JNDI_MCD";
	public static final String MCD_DBTYPE = "MCD_DBTYPE";
	public static final String MCD_TABLESPACE = "MCD_TABLESPACE";
	public static final String MCD_SCHEMA = "MCD_SCHEMA";
	public static final String MCD_TMP_TABLE = "MCD_TMP_TABLE";
	public static final String MCD_TMP_TABLE_KEYCOLUMN = "MCD_TMP_TABLE_KEYCOLUMN";
	public static final String ALL_DIM_CITY = "999";
	public static final int BIG_DECIMAL_SCALE = 2;
	public static final String OLD_CI_JNDI = "OLD_CI_JNDI";
	public static final String OLD_CI_BACK_JNDI = "OLD_CI_BACK_JNDI";
	public static final String OLD_CI_DBTYPE = "OLD_CI_DBTYPE";
	public static final String OLD_CI_BACK_DBTYPE = "OLD_CI_BACK_DBTYPE";
	public static final String OLD_CI_BACK_TABLESPACE = "OLD_CI_TABLESPACE_BACK";
	public static final String OLD_CI_BACK_SCHEMA = "OLD_CI_BACK_SCHEMA";
	public static final String OLD_CI_TMP_TABLE = "OLD_CI_TMP_TABLE";
	public static final String OLD_CI_KEYCOLUMN = "OLD_CI_KEYCOLUMN";
	public static final String OLD_CI_SYS_ID = "OLD_CI_SYS_ID";
	public static final String OLD_CI_EXPORT_SQL = "OLD_CI_EXPORT_SQL";
	public static final String OLD_CI_INSERT_DATA_SQL = "OLD_CI_INSERT_DATA_SQL";
	public static final String OLD_CI_INSERT_GROUPINFO_SQL = "OLD_CI_INSERT_GROUPINFO_SQL";
	public static final String CM_JNDI = "CM_JNDI";
	public static final String CM_BACK_JNDI = "CM_BACK_JNDI";
	public static final String CM_DBTYPE = "CM_DBTYPE";
	public static final String CM_BACK_DBTYPE = "CM_BACK_DBTYPE";
	public static final String CM_BACK_TABLESPACE = "CM_TABLESPACE_BACK";
	public static final String CM_BACK_SCHEMA = "CM_BACK_SCHEMA";
	public static final String CM_TMP_TABLE = "CM_TMP_TABLE";
	public static final String CM_KEYCOLUMN = "CM_KEYCOLUMN";
	public static final String CM_SYS_ID = "CM_SYS_ID";
	public static final String CM_EXPORT_SQL = "CM_EXPORT_SQL";
	public static final String CM_INSERT_DATA_SQL = "CM_INSERT_DATA_SQL";
	public static final String CM_INSERT_GROUPINFO_SQL = "CM_INSERT_GROUPINFO_SQL";
	public static final String CMTARGET_JNDI = "CMTARGET_JNDI";
	public static final String CMTARGET_BACK_JNDI = "CMTARGET_BACK_JNDI";
	public static final String CMTARGET_DBTYPE = "CMTARGET_DBTYPE";
	public static final String CMTARGET_BACK_DBTYPE = "CMTARGET_BACK_DBTYPE";
	public static final String CMTARGET_BACK_TABLESPACE = "CMTARGET_TABLESPACE_BACK";
	public static final String CMTARGET_BACK_SCHEMA = "CMTARGET_BACK_SCHEMA";
	public static final String CMTARGET_TMP_TABLE = "CMTARGET_TMP_TABLE";
	public static final String CMTARGET_KEYCOLUMN = "CMTARGET_KEYCOLUMN";
	public static final String CMTARGET_SYS_ID = "CMTARGET_SYS_ID";
	public static final String CMTARGET_EXPORT_SQL = "CMTARGET_EXPORT_SQL";
	public static final String CMTARGET_INSERT_DATA_SQL = "CMTARGET_INSERT_DATA_SQL";
	public static final String CMTARGET_INSERT_GROUPINFO_SQL = "CMTARGET_INSERT_GROUPINFO_SQL";
	public static final String CMTARGET_WEBSERVICE_URL = "CMTARGET_WEBSERVICE_URL";
	public static final String LT = "<";
	public static final String GT = ">";
	public static final String LE = "<=";
	public static final String GE = ">=";
	public static final String NE = "<>";
	public static final String EQ = "=";
	public static final String HOT_LABELS = "HOT_LABELS";
	public static final String HOT_CUSTOMS = "HOT_CUSTOMS";
	public static final String LABEL_EXACT_VALUE_TABLE = "LABEL_EXACT_VALUE_TABLE";
	public static final String LABEL_EXACT_VALUE_TABLE_POSTFIX = "YYMMDDHHMISSTTTTTT";
	public static final String LABEL_EXACT_VALUE_TABLE_COLUMN = "VALUE_ID";
	public static final String CI_SYS_TABLE_MAP = "CI_SYS_TABLE_MAP";
	public static final String TABEL_ALL_LABEL_COLUMN_NAME = "TABEL_ALL_LABEL_COLUMN_NAME";
	public static final String CI_DIM_TABLE_MAP = "CI_DIM_TABLE_MAP";
	public static final String CI_MARKET_SCENE_MAP = "CI_MARKET_SCENE_MAP";
	public static final String ZJ_USER = "ZJ_USER";
	public static final char UNION = 8746;
	public static final char INTERSECT = 8745;
	public static final char EXCEPT = 45;
	public static final char LEFT_Q = 40;
	public static final char RIGHT_Q = 41;
	public static final String SIGN_PERCENT = "%";
	public static final String SIGN_EQUALS = "=";
	public static final String SINGL_EQUOTES = "'";

	public CommonConstants()
	{
	}

}
